import React from 'react';
import {
  BarChart3,
  Bitcoin,
  Boxes,
  CalendarDays,
  Camera,
  Video,
  CheckCircle2,
  ClipboardList,
  Compass,
  Download,
  ExternalLink,
  Eye,
  Facebook,
  FileDown,
  FileText,
  Folder,
  Gem,
  Headphones,
  ContactRound,
  Image as ImageIcon,
  IndianRupee,
  Instagram,
  Landmark,
  Layers,
  Link,
  Linkedin,
  Loader2,
  Menu,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  Music,
  Palette,
  Pencil,
  Phone,
  PieChart,
  Pointer,
  Printer,
  RefreshCcw,
  Rocket,
  Search,
  Sparkles,
  Smartphone,
  Timer,
  Ticket,
  Trash2,
  TrendingUp,
  Twitter,
  Youtube,
  Wallet,
  Wifi,
  Zap,
  X,
  XCircle
} from 'lucide-react';

const ICONS = {
  dashboard: BarChart3,
  library: Folder,
  folder: Folder,
  bulk: Boxes,
  template: Layers,
  static: Palette,
  compass: Compass,
  rocket: Rocket,
  trend: TrendingUp,
  printer: Printer,
  download: Download,
  external: ExternalLink,
  downloadFile: FileDown,
  link: Link,
  image: ImageIcon,
  camera: Camera,
  video: Video,
  edit: Pencil,
  stats: PieChart,
  refresh: RefreshCcw,
  trash: Trash2,
  loader: Loader2,
  search: Search,
  sparkles: Sparkles,
  lightning: Zap,
  success: CheckCircle2,
  error: XCircle,
  menu: Menu,
  phone: Phone,
  message: MessageCircle,
  sms: MessageSquare,
  smartphone: Smartphone,
  map: MapPin,
  calendar: CalendarDays,
  wifi: Wifi,
  contact: ContactRound,
  id: ContactRound,
  file: FileText,
  audio: Music,
  ticket: Ticket,
  crypto: Bitcoin,
  wallet: Wallet,
  upi: IndianRupee,
  bank: Landmark,
  pix: Gem,
  facebook: Facebook,
  instagram: Instagram,
  linkedin: Linkedin,
  twitter: Twitter,
  youtube: Youtube,
  eye: Eye,
  pointer: Pointer,
  clipboard: ClipboardList,
  headphones: Headphones,
  envelope: Mail,
  boxes: Boxes,
  chart: BarChart3,
  timer: Timer,
  close: X
};

export function Icon({ name, size = 18, strokeWidth = 2, className, ...rest }) {
  const Component = ICONS[name];
  if (!Component) return null;
  return (
    <Component
      aria-hidden="true"
      className={className}
      size={size}
      strokeWidth={strokeWidth}
      {...rest}
    />
  );
}

export default Icon;
